framework:
  secret: '%env(APP_SECRET)%'
  handle_all_throwables: true
  http_method_override: false

  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
