<?php

declare(strict_types=1);

namespace DoctrineMigrations\Currencing;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260914144500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align the reconciled PostgreSQL schema with the current Doctrine metadata.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE currency_currency ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE currency_currency ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE currency_currency ALTER first_title TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE currency_currency ALTER active SET DEFAULT true');
        $this->addSql('ALTER TABLE currency_currency ALTER enabled SET DEFAULT true');
        $this->addSql('ALTER INDEX IF EXISTS uniq_currency_uuid RENAME TO UNIQ_593EDE2CD17F50A6');
        $this->addSql('ALTER INDEX IF EXISTS uniq_currency_slug RENAME TO UNIQ_593EDE2C989D9B62');
        $this->addSql('ALTER TABLE currency_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE currency_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE currency_translation ALTER active SET DEFAULT true');
        $this->addSql('ALTER TABLE currency_translation ALTER enabled SET DEFAULT true');
        $this->addSql('ALTER INDEX IF EXISTS uniq_currency_translation_uuid RENAME TO UNIQ_5814BCED17F50A6');
        $this->addSql('ALTER INDEX IF EXISTS uniq_currency_translation_slug RENAME TO UNIQ_5814BCE989D9B62');
        $this->addSql('ALTER INDEX IF EXISTS idx_currency_translation_currency RENAME TO IDX_5814BCE38248176');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigration('Doctrine metadata alignment is intentionally forward-only.');
    }
}
