<?php

declare(strict_types=1);

namespace DoctrineMigrations\Currencing;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260914143500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Normalize Currencing currency id generation to canonical sequence-backed semantics.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("DO $$ BEGIN IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'currency_currency' AND column_name = 'id' AND is_identity = 'YES') THEN ALTER TABLE currency_currency ALTER COLUMN id DROP IDENTITY; END IF; END $$");
        $this->addSql('CREATE SEQUENCE IF NOT EXISTS currency_currency_id_seq');
        $this->addSql('ALTER SEQUENCE currency_currency_id_seq OWNED BY currency_currency.id');
        $this->addSql("ALTER TABLE currency_currency ALTER COLUMN id SET DEFAULT nextval('currency_currency_id_seq')");
        $this->addSql("SELECT setval('currency_currency_id_seq', COALESCE((SELECT MAX(id) FROM currency_currency), 0) + 1, false)");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE currency_currency ALTER COLUMN id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS currency_currency_id_seq');
        $this->addSql('ALTER TABLE currency_currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
