<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260503000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create PostgreSQL currency metadata table for Currencing component.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            $this->connection->getDatabasePlatform()->getName() !== 'postgresql',
            'Currencing M17 migrations are PostgreSQL-first and require the postgresql platform.'
        );

        $this->addSql('CREATE TABLE currency_currency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(3) NOT NULL, numeric_code VARCHAR(3) DEFAULT NULL, minor_unit SMALLINT NOT NULL, symbol VARCHAR(16) DEFAULT NULL, display_name VARCHAR(128) DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_currency_currency_code ON currency_currency (code)');
        $this->addSql('CREATE INDEX idx_currency_currency_active_code ON currency_currency (active, code)');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            $this->connection->getDatabasePlatform()->getName() !== 'postgresql',
            'Currencing M17 migrations are PostgreSQL-first and require the postgresql platform.'
        );

        $this->addSql('DROP TABLE currency_currency');
    }
}
